'use client';
import { ChangeEvent, useEffect, useMemo, useState } from 'react';
import { KEY, MODULES, TOPICS, State, emptyState, firstPass, makeRevisions, mockCredit, readiness, revisionCredit, today, weekDays } from '../lib/tracker';
type Tab='dashboard'|'topics'|'revision'|'log'|'mocks';
const fmt=(n:number)=>n.toFixed(1);
export default function Tracker(){
 const [state,setState]=useState<State>(emptyState),[loaded,setLoaded]=useState(false),[tab,setTab]=useState<Tab>('dashboard'),[active,setActive]=useState<string|null>(null),[filter,setFilter]=useState('due'),[session,setSession]=useState({date:today(),hours:1,subjectId:'',moduleId:''});
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw)setState({...emptyState(),...JSON.parse(raw)});}finally{setLoaded(true)}},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(KEY,JSON.stringify(state))},[state,loaded]);
 const update=(fn:(s:State)=>State)=>setState(s=>fn(s)); const selected=MODULES.find(m=>m.id===active);
 const moduleName=(id:string)=>MODULES.find(m=>m.id===id)?.title||'General study';
 const complete=(id:string)=>update(s=>{const date=today();return {...s,completionDates:{...s.completionDates,[id]:date},revisionTasks:[...s.revisionTasks.filter(t=>t.moduleId!==id),...makeRevisions(id,date,s.examDate)]}});
 const incomplete=(id:string)=>update(s=>{const attempts=s.attempts[id]||0;return attempts>=2?s:{...s,attempts:{...s.attempts,[id]:attempts+1}}});
 const uncomplete=(id:string)=>update(s=>{const c={...s.completionDates};delete c[id];const a={...s.attempts};delete a[id];return {...s,completionDates:c,attempts:a,revisionTasks:s.revisionTasks.filter(t=>t.moduleId!==id)}});
 const addLog=(moduleIdOverride?:string)=>{if(!session.hours||session.hours<=0)return;update(s=>({...s,logs:[{id:crypto.randomUUID(),date:session.date,moduleId:moduleIdOverride??session.moduleId,minutes:Math.round(Number(session.hours)*60)},...s.logs]}));setSession({...session,hours:1});setActive(null)};
 const exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download=`cfa-level-2-tracker-${today()}.json`;a.click();URL.revokeObjectURL(a.href)};
 const importData=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const n=JSON.parse(String(r.result));if(n.schemaVersion!==1)throw new Error();setState({...emptyState(),...n})}catch{alert('That backup is not compatible with this tracker.')}};r.readAsText(f)};
 if(!loaded)return null;
 if(!state.setup)return <main className="welcome"><section className="welcome-card"><p className="eyebrow">CFA LEVEL II · COMMAND CENTER</p><h1>Make every study session count.</h1><p className="lede">A calm, module-first tracker for your 51-module journey. Set an exam date to create your personal study command center.</p><label>Exam date<input type="date" value={state.examDate||''} onChange={e=>setState(s=>({...s,examDate:e.target.value||null}))}/></label><button className="primary" disabled={!state.examDate} onClick={()=>update(s=>({...s,setup:true}))}>Enter tracker</button></section></main>;
 const totalHours=state.logs.reduce((a,l)=>a+l.minutes,0)/60; const completed=Object.keys(state.completionDates).length; const due=state.revisionTasks.filter(x=>!x.done&&x.due<=today()); const examDays=state.examDate?Math.max(0,Math.ceil((new Date(state.examDate+'T12:00').getTime()-new Date(today()+'T12:00').getTime())/864e5)):0;
 return <main><header><div><p className="eyebrow">CFA LEVEL II · {state.examDate?new Date(state.examDate+'T12:00').toLocaleString('en',{month:'long',year:'numeric'}):'EXAM DATE'}</p><h1>Study Tracker <span>& Command Center</span></h1><p>Plan, execute, and measure the 51-module roadmap.</p></div><div className="count"><strong>{examDays}</strong><span>days to exam</span><input aria-label="Exam date" type="date" value={state.examDate||''} onChange={e=>update(s=>({...s,examDate:e.target.value||null}))}/></div></header>
 <nav>{(['dashboard','topics','revision','log','mocks'] as Tab[]).map(x=><button key={x} className={tab===x?'selected':''} onClick={()=>setTab(x)}>{x==='log'?'Study Log':x[0].toUpperCase()+x.slice(1)}</button>)}<span/><button onClick={exportData}>Export</button><label className="import">Import<input type="file" accept="application/json" onChange={importData}/></label></nav>
 {tab==='dashboard'&&<Dashboard s={state} completed={completed} hours={totalHours} due={due} onTab={setTab}/>} {tab==='topics'&&<Topics s={state} onOpen={setActive}/>} {tab==='revision'&&<Revision s={state} filter={filter} setFilter={setFilter} toggle={id=>update(s=>({...s,revisionTasks:s.revisionTasks.map(t=>t.id===id?{...t,done:!t.done}:t)}))} quiz={(id)=>update(s=>({...s,quizzes:{...s.quizzes,[id]:{...s.quizzes[id],done:!s.quizzes[id].done}}}))} date={(id,v)=>update(s=>({...s,quizzes:{...s.quizzes,[id]:{...s.quizzes[id],targetDate:v}}}))}/>} {tab==='log'&&<Log s={state} session={session} setSession={setSession} add={addLog} onOpen={setActive} name={moduleName}/>} {tab==='mocks'&&<Mocks s={state} update={update}/>} 
 {selected&&<Dialog module={selected} s={state} session={session} setSession={setSession} close={()=>setActive(null)} complete={complete} incomplete={incomplete} uncomplete={uncomplete} addLog={addLog}/>} 
 </main>
}
function Dashboard({s,completed,hours,due,onTab}:{s:State;completed:number;hours:number;due:any[];onTab:(t:Tab)=>void}){const r=readiness(s),days=weekDays();return <section className="space"><div className="dashboard-top"><article className="ring card"><div className="circle" style={{'--p':`${r}%`} as React.CSSProperties}><b>{fmt(r)}%</b><small>readiness</small></div><div><h2>Exam readiness</h2><p>Built from first pass, revision, and completed mocks.</p></div></article><article className="card pillars"><Pillar label="First pass" value={firstPass(s)} max={50}/><Pillar label="Spaced revision" value={revisionCredit(s)} max={20}/><Pillar label="Mock gauntlet" value={mockCredit(s)} max={30}/></article></div><div className="metrics"><Metric value={`${fmt(hours)}h`} label="Cumulative study"/><Metric value={`${s.logs.filter(l=>days.includes(l.date)).reduce((a,l)=>a+l.minutes,0)/60}h`} label="This week"/><Metric value={`${completed} / 51`} label="Modules completed"/><Metric value={`${s.logs.length}`} label="Sessions logged"/></div><div className="split"><article className="card"><div className="card-title"><h2>Tasks due today</h2><button onClick={()=>onTab('revision')}>View revision</button></div>{due.length?<ul className="tasks">{due.slice(0,6).map(t=><li key={t.id}><span>{MODULES.find(m=>m.id===t.moduleId)?.title}</span><em>{t.kind}</em></li>)}</ul>:<p className="empty">Nothing is due. A quiet day is a good day.</p>}</article><article className="card"><h2>This week</h2><div className="week">{days.map(d=>{const m=s.logs.filter(l=>l.date===d).reduce((a,l)=>a+l.minutes,0);return <div key={d} className={s.rest.includes(d)?'rest':''}><b>{new Date(d+'T12').toLocaleDateString('en',{weekday:'short'})}</b><span>{s.rest.includes(d)?'REST':m?`${Math.round(m/6)/10}h`:'—'}</span></div>})}</div></article></div></section>}
function Pillar({label,value,max}:{label:string;value:number;max:number}){return <div><span>{label}<b>{fmt(value)} / {max}</b></span><i><i style={{width:`${value/max*100}%`}}/></i></div>}; function Metric({value,label}:{value:string;label:string}){return <article className="card metric"><b>{value}</b><span>{label}</span></article>}
function Topics({s,onOpen}:{s:State;onOpen:(id:string)=>void}){let n=0;return <section className="space"><div className="intro"><p className="eyebrow">CURRICULUM</p><h2>Learning modules</h2><p>Planned hours are estimated allocations; completion is independent of logged time.</p></div><div className="topic-grid">{TOPICS.map(t=>{const ms=MODULES.filter(m=>m.topicId===t.id);return <article className="card topic" key={t.id}><header><div><h2>{t.name}</h2><p>{t.weight}% exam weight · {ms.length} modules</p></div><b>{ms.filter(m=>s.completionDates[m.id]).length}/{ms.length}</b></header>{ms.map(m=>{n++;const status=s.completionDates[m.id]?'Completed':s.attempts[m.id]?'Incomplete':'Not started';return <button className="module" key={m.id} onClick={()=>onOpen(m.id)}><i className={status==='Completed'?'done':''}/><span className="num">{String(n).padStart(2,'0')}</span><strong>{m.title}</strong><span>{m.planned}h</span><em>{status}</em></button>})}</article>})}</div></section>}
function Revision({s,filter,setFilter,toggle,quiz,date}:{s:State;filter:string;setFilter:(x:string)=>void;toggle:(id:string)=>void;quiz:(id:string)=>void;date:(id:string,v:string)=>void}){const inSevenDays=(d:string)=>{const end=new Date(`${today()}T12:00:00`);end.setDate(end.getDate()+7);return new Date(`${d}T12:00:00`)<=end};const tasks=s.revisionTasks.filter(t=>filter==='done'?t.done:filter==='overdue'?(!t.done&&t.due<today()):filter==='upcoming'?(!t.done&&t.due>today()&&inSevenDays(t.due)):!t.done&&t.due<=today());return <section className="space"><div className="intro"><p className="eyebrow">SPACED REPETITION</p><h2>Revision queue</h2></div><div className="filters">{[['due','Due today'],['overdue','Overdue'],['upcoming','Next 7 days'],['done','History']].map(([k,l])=><button className={filter===k?'selected':''} onClick={()=>setFilter(k)} key={k}>{l}</button>)}</div><div className="task-list">{tasks.length?tasks.map(t=><article className="card task" key={t.id}><button className={t.done?'check done':''} onClick={()=>toggle(t.id)}/><div><b>{MODULES.find(m=>m.id===t.moduleId)?.title}</b><span>{t.kind} · {t.due}</span></div><em>{t.reward?'Core review':'Retention'}</em></article>):<p className="empty">No tasks in this view.</p>}</div><div className="section-head"><p className="eyebrow">EXECUTION</p><h2>Subject quizzes</h2></div><div className="quiz-grid">{TOPICS.map(t=>{const q=s.quizzes[t.id];return <article className="card quiz" key={t.id}><div><b>{t.name}</b><span>{q.done?'Complete':'Not completed'}</span></div><input type="date" value={q.targetDate} onChange={e=>date(t.id,e.target.value)}/><button className={q.done?'primary subtle':'secondary'} onClick={()=>quiz(t.id)}>{q.done?'Completed':'Mark done'}</button></article>})}</div></section>}
function Log({s,session,setSession,add,onOpen,name}:{s:State;session:any;setSession:(x:any)=>void;add:()=>void;onOpen:(id:string)=>void;name:(id:string)=>string}){const h=s.logs.reduce((a,l)=>a+l.minutes,0)/60;const visible=MODULES.filter(m=>!session.subjectId||m.topicId===session.subjectId);return <section className="space"><div className="intro"><p className="eyebrow">STUDY LOG</p><h2>Log a session</h2><p>Time informs activity analytics only, never completion.</p></div><article className="card form"><label>Date<input type="date" value={session.date} onChange={e=>setSession({...session,date:e.target.value})}/></label><label>Duration (hours)<input type="number" step="0.25" min="0.25" value={session.hours} onChange={e=>setSession({...session,hours:e.target.value})}/></label><label>Subject<select value={session.subjectId} onChange={e=>setSession({...session,subjectId:e.target.value,moduleId:''})}><option value="">General study</option>{TOPICS.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label>Learning module<select disabled={!session.subjectId} value={session.moduleId} onChange={e=>setSession({...session,moduleId:e.target.value})}><option value="">{session.subjectId?'Select a module':'Select a subject first'}</option>{visible.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><button className="primary" onClick={add}>Log session</button></article><div className="metrics"><Metric value={`${fmt(h)}h`} label="Total hours"/><Metric value={`${s.logs.length}`} label="Sessions"/><Metric value={s.logs.length?`${fmt(s.logs.reduce((a,l)=>a+l.minutes,0)/60/s.logs.length)}h`:'—'} label="Average session"/></div><article className="card table"><h2>Session record</h2>{s.logs.length?<table><tbody>{s.logs.map(l=><tr key={l.id}><td>{l.date}</td><td>{name(l.moduleId)}</td><td>{fmt(l.minutes/60)}h</td><td>{l.moduleId&&<button onClick={()=>onOpen(l.moduleId)}>Open module</button>}</td></tr>)}</tbody></table>:<p className="empty">Your logged sessions will appear here.</p>}</article></section>}
function Mocks({s,update}:{s:State;update:(f:(s:State)=>State)=>void}){const finish=(id:string)=>{const v=prompt('Mock score (0–100)');if(v===null)return;const score=Math.max(0,Math.min(100,Number(v)));if(Number.isNaN(score))return;update(s=>({...s,mocks:s.mocks.map(m=>m.id===id?{...m,done:true,score,completedAt:today()}:m)}))};return <section className="space"><div className="intro"><p className="eyebrow">MOCK GAUNTLET</p><h2>Eight full mocks</h2><p>Each completed mock contributes 3.75% to readiness; score is shown only in the trend.</p></div><div className="mock-grid">{s.mocks.map((m,i)=><article className="card mock" key={m.id}><p>FULL MOCK {String(i+1).padStart(2,'0')}</p><b>{m.done?`${m.score}%`:'Not attempted'}</b><label>Target date<input type="date" value={m.targetDate} onChange={e=>update(s=>({...s,mocks:s.mocks.map(x=>x.id===m.id?{...x,targetDate:e.target.value}:x)}))}/></label><button className={m.done?'secondary':'primary'} disabled={m.done} onClick={()=>finish(m.id)}>{m.done?'Completed':'Record score'}</button></article>)}</div><article className="card chart"><h2>Score trend</h2><div className="chart-line">{s.mocks.filter(m=>m.done).length?s.mocks.filter(m=>m.done).map(m=><span key={m.id} style={{height:`${m.score}%`}} title={`${m.score}%`}/>):<p className="empty">Complete a mock to begin the trend.</p>}</div></article></section>}
function Dialog({module,s,session,setSession,close,complete,incomplete,uncomplete,addLog}:{module:any;s:State;session:any;setSession:(x:any)=>void;close:()=>void;complete:(id:string)=>void;incomplete:(id:string)=>void;uncomplete:(id:string)=>void;addLog:(moduleId?:string)=>void}){const done=!!s.completionDates[module.id],attempts=s.attempts[module.id]||0;return <div className="overlay" onMouseDown={close}><section className="dialog card" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={close}>×</button><p className="eyebrow">{TOPICS.find(t=>t.id===module.topicId)?.name}</p><h2>{module.title}</h2><p>{module.planned} estimated planned hours · {done?'Completed':attempts?`Incomplete attempt ${attempts} of 2`:'Not started'}</p><div className="dialog-form"><label>Study date<input type="date" value={session.date} onChange={e=>setSession({...session,date:e.target.value,moduleId:module.id})}/></label><label>Duration (hours)<input type="number" step="0.25" min="0.25" value={session.hours} onChange={e=>setSession({...session,hours:e.target.value,moduleId:module.id})}/></label><button className="secondary" onClick={()=>addLog(module.id)}>Log session</button></div><div className="actions">{done?<button className="secondary" onClick={()=>uncomplete(module.id)}>Uncheck completed</button>:<><button className="primary" onClick={()=>{complete(module.id);close()}}>Mark completed</button><button className="secondary" disabled={attempts>=2} onClick={()=>{incomplete(module.id);close()}}>Mark incomplete {attempts>=2?'(blocked)':''}</button></>}</div><p className="hint">Completion creates Day 1, Day 7 and Day 21 reviews. Retention reviews run every 21 days until two months before your exam.</p></section></div>}
