'use client';

import { useEffect, useMemo, useState } from 'react';

const STORE = 'cfa-l2-tracker-v1';
const SCHEMA_VERSION = 1;
const TOTAL_MODULES = 51;
const REVISION_WEIGHT = 20;
const CORE_REWARD = REVISION_WEIGHT / (TOTAL_MODULES * 3);
const MOCK_REWARD = 3.75;
const TOPICS = [
  { id:'quantitativeMethods', name:'Quantitative Methods', weight:7.5, hours:[3.5,3.5,3,3,3.5,3,3], modules:['Basics of Multiple Regression and Underlying Assumptions','Evaluating Regression Model Fit and Interpreting Model Results','Model Misspecification','Extensions of Multiple Regression','Time-Series Analysis','Machine Learning','Big Data Projects'] },
  { id:'economics', name:'Economics', weight:7.5, hours:[11,11.5], modules:['Currency Exchange Rates: Understanding Equilibrium Value','Economic Growth'] },
  { id:'financialStatementAnalysis', name:'Financial Statement Analysis', weight:12.5, hours:[6,6,6,6,6,7.5], modules:['Intercorporate Investments','Employee Compensation: Post Employment and Share-based','Multinational Operations','Analysis of Financial Institutions','Evaluating Quality of Financial Reports','Integration of Financial Statement Analysis Techniques'] },
  { id:'corporateIssuers', name:'Corporate Finance', weight:7.5, hours:[5.5,5.5,5.5,6], modules:['Analysis of Dividends and Share Repurchases','Environmental, Social, and Governance (ESG) Considerations in Investment Analysis','Cost of Capital: Advanced Topics','Corporate Restructuring'] },
  { id:'equities', name:'Equities', weight:12.5, hours:[6.5,6,6,6,6,7], modules:['Equity Valuation: Applications and Processes','Discounted Dividend Valuation','Free Cash Flow Valuation','Market-Based Valuation: Price and Enterprise Value Multiples','Residual Income Valuation','Private Company Valuation'] },
  { id:'fixedIncome', name:'Fixed Income', weight:12.5, hours:[7.5,7.5,7.5,7.5,7.5], modules:['The Term Structure & Interest Rate Dynamics','The Arbitrage Free Valuation Framework','Valuation & Analysis of Bonds with Embedded Options','Credit Analysis Models','Credit Default Swaps'] },
  { id:'derivatives', name:'Derivatives', weight:7.5, hours:[11,11.5], modules:['Pricing & Valuation of Forward Commitments','Valuation of Contingent Claims'] },
  { id:'alternativeInvestments', name:'Alternative Investments', weight:7.5, hours:[5.5,5.5,5.5,6], modules:['Introduction to Commodities & Commodity Derivatives','Overview of Types of Real Estate Investment','Investments in Real Estate Through Publicly Traded Securities','Hedge Fund Strategies'] },
  { id:'portfolioConstruction', name:'Portfolio Construction', weight:12.5, hours:[6,6,6,6,6.5,7], modules:['Economics and Investment Markets','Analysis of Active Portfolio Management','Exchange-Traded Funds: Mechanics & Applications','Using Multifactor Models','Measuring & Managing Market Risk','Backtesting and Simulation'] },
  { id:'ethicalAndProfessionalStandards', name:'Ethical and Professional Standards', weight:12.5, hours:[4,4,4,4,4,4,4,4,5.5], modules:['Code of Ethics and Standards of Professional Conduct','Guidance for Standard I: Professionalism','Guidance for Standard II: Integrity of Capital Markets','Guidance for Standard III: Duties to Clients','Guidance for Standard IV: Duties to Employers','Guidance for Standard V: Investment Analysis, Recommendations, and Actions','Guidance for Standard VI: Conflicts of Interest','Guidance for Standard VII: Responsibilities as a CFA Institute Member or CFA Candidate','Application of the Code and Standards: Level II'] }
];
const MODULES = TOPICS.flatMap(topic => topic.modules.map((title,index) => ({ id:`${topic.id}:${index+1}`, topicId:topic.id, topicName:topic.name, number:index+1, title, plannedHours:topic.hours[index] })));
const MODULE_BY_ID = Object.fromEntries(MODULES.map(m => [m.id,m]));
const QUIZ_NAMES = TOPICS.map(t => ({topicId:t.id,topicName:t.name}));
const MOCKS = Array.from({length:8},(_,i)=>({id:`mock-${i+1}`,title:`Full Mock ${i+1}`,targetDate:null,score:null,done:false,completedAt:null}));

const isoToday = () => { const d=new Date(); return new Date(d.getFullYear(),d.getMonth(),d.getDate()).toISOString().slice(0,10); };
const parseDate = value => { const d=new Date(`${value}T12:00:00`); return Number.isNaN(d.getTime())?null:d; };
const addDays = (value,n) => { const d=parseDate(value); if(!d)return value; d.setDate(d.getDate()+n); return d.toISOString().slice(0,10); };
const subtractMonths = (value,n) => { const d=parseDate(value); if(!d)return value; const day=d.getDate(); d.setDate(1); d.setMonth(d.getMonth()-n); const last=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(); d.setDate(Math.min(day,last)); return d.toISOString().slice(0,10); };
const formatDate = value => { const d=parseDate(value); return d?d.toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'; };
const formatShort = value => { const d=parseDate(value); return d?d.toLocaleDateString('en-IN',{day:'2-digit',month:'short'}):'—'; };
const daysRemaining = exam => { if(!exam)return 0; const a=parseDate(isoToday()),b=parseDate(exam); return Math.max(0,Math.ceil((b-a)/86400000)); };
const isoWeekKey = date => { const d=parseDate(date); const day=d.getDay()||7; d.setDate(d.getDate()+4-day); const yearStart=new Date(d.getFullYear(),0,1); return `${d.getFullYear()}-${Math.ceil((((d-yearStart)/86400000)+1)/7)}`; };
const restDateForWeek = (rest,today) => rest.find(x=>isoWeekKey(x)===isoWeekKey(today));

function blankState(){
  return {schemaVersion:SCHEMA_VERSION,examDate:null,readDone:[],readingDone:{},readingProgress:{},completionDates:{},revisionTasks:[],revisionHistory:[],revisionReadinessCredit:0,subjectQuizzes:QUIZ_NAMES.map(q=>({topicId:q.topicId,topicName:q.topicName,targetDate:null,done:false})),mocks:MOCKS.map(m=>({...m})),logs:[],rest:[],setupComplete:false};
}
function normalize(raw){
  const base=blankState();
  if(!raw||typeof raw!=='object')return base;
  const next={...base,...raw};
  next.schemaVersion=SCHEMA_VERSION;
  next.examDate=typeof raw.examDate==='string'?raw.examDate:null;
  next.readDone=Array.isArray(raw.readDone)?[...new Set(raw.readDone.filter(id=>MODULE_BY_ID[id]))]:[];
  next.readingDone=raw.readingDone&&typeof raw.readingDone==='object'?raw.readingDone:{};
  next.readingProgress=raw.readingProgress&&typeof raw.readingProgress==='object'?raw.readingProgress:{};
  next.completionDates=raw.completionDates&&typeof raw.completionDates==='object'?raw.completionDates:{};
  next.revisionTasks=Array.isArray(raw.revisionTasks)?raw.revisionTasks:[];
  next.revisionHistory=Array.isArray(raw.revisionHistory)?raw.revisionHistory:[];
  next.revisionReadinessCredit=Number(raw.revisionReadinessCredit)||0;
  next.subjectQuizzes=QUIZ_NAMES.map(q=>{const found=(raw.subjectQuizzes||[]).find(x=>x.topicId===q.topicId);return {...q,targetDate:found?.targetDate||null,done:Boolean(found?.done)}});
  next.mocks=MOCKS.map(m=>{const found=(raw.mocks||[]).find(x=>x.id===m.id);return {...m,targetDate:found?.targetDate||null,score:found?.score===''||found?.score==null?null:Number(found.score),done:Boolean(found?.done),completedAt:found?.completedAt||null}});
  next.logs=Array.isArray(raw.logs)?raw.logs.filter(x=>x&&x.id&&x.date&&Number(x.durationMinutes)>0&&MODULE_BY_ID[x.moduleId]).map(x=>({...x,durationMinutes:Number(x.durationMinutes)})):[];
  next.rest=Array.isArray(raw.rest)?raw.rest.filter(x=>typeof x==='string'):[];
  next.setupComplete=Boolean(raw.setupComplete&&next.examDate);
  return next;
}
function revisionSchedule(module,completionDate,examDate){
  const tasks=[1,7,21].map((offset,index)=>({taskId:`${module.id}:d${offset}`,moduleId:module.id,moduleTitle:module.title,reviewType:`D+${offset}`,dueDate:addDays(completionDate,offset),status:'pending',completedAt:null,rewardCredit:CORE_REWARD,core:true,index}));
  const cutoff=examDate?subtractMonths(examDate,2):null;
  if(cutoff){let offset=42;let index=4;while(addDays(completionDate,offset)<=cutoff){tasks.push({taskId:`${module.id}:b${offset}`,moduleId:module.id,moduleTitle:module.title,reviewType:`D+${offset} retention`,dueDate:addDays(completionDate,offset),status:'pending',completedAt:null,rewardCredit:0,core:false,index});offset+=21;index++;}}
  return tasks;
}
function readiness(state){
  const first=TOPICS.reduce((sum,topic)=>{const completed=topic.modules.reduce((n,_,i)=>n+(state.readingProgress[`${topic.id}:${i+1}`]?.status==='completed'?1:state.readingProgress[`${topic.id}:${i+1}`]?.status==='incomplete'?0.5:0),0);return sum+(topic.weight/100)*50*(completed/topic.modules.length);},0);
  const revision=Math.min(20,state.revisionTasks.reduce((s,t)=>s+(t.status==='completed'?Number(t.rewardCredit||0):0),0));
  const mocks=state.mocks.filter(m=>m.done).length*MOCK_REWARD;
  return {first,revision,mocks,total:Math.min(100,first+revision+mocks)};
}
function weekHours(state,today){const d=parseDate(today);const day=d.getDay()||7;const monday=new Date(d);monday.setDate(d.getDate()-day+1);return state.logs.filter(l=>{const x=parseDate(l.date);return x>=monday&&x<=d;}).reduce((s,l)=>s+l.durationMinutes/60,0);}
function streak(state,today){let cursor=today,count=0;while(true){const rest=state.rest.includes(cursor);const studied=state.logs.some(l=>l.date===cursor&&l.durationMinutes>0);if(rest||studied){count++;const d=parseDate(cursor);d.setDate(d.getDate()-1);cursor=d.toISOString().slice(0,10);}else break;}return count;}
function tasksDueToday(state,today){const revisions=state.revisionTasks.filter(t=>t.status!=='completed'&&t.dueDate===today).map(t=>({type:'revision',id:t.taskId,title:t.moduleTitle,meta:t.reviewType}));const quizzes=state.subjectQuizzes.filter(q=>!q.done&&q.targetDate===today).map(q=>({type:'quiz',id:q.topicId,title:q.topicName,meta:'Subject quiz'}));return [...revisions,...quizzes];}
function chartPoints(mocks){const done=mocks.filter(m=>m.done&&m.completedAt&&typeof m.score==='number');if(!done.length)return '';return done.map((m,i)=>{const x=5+(i/(Math.max(done.length-1,1)))*90;const y=95-(m.score/100)*90;return `${x},${y}`;}).join(' ');}

export default function Home(){
  const [state,setState]=useState(blankState());
  const [hydrated,setHydrated]=useState(false);
  const [tab,setTab]=useState('Dashboard');
  const [moduleDialog,setModuleDialog]=useState(null);
  const [sessionDate,setSessionDate]=useState(isoToday());
  const [sessionMinutes,setSessionMinutes]=useState('60');
  const [moduleSelect,setModuleSelect]=useState('');
  const [revisionFilter,setRevisionFilter]=useState('Due Today');
  const [mockDialog,setMockDialog]=useState(null);
  const [mockScore,setMockScore]=useState('');
  const [restPrompt,setRestPrompt]=useState(false);
  const [setupDate,setSetupDate]=useState('');
  const [confirmImport,setConfirmImport]=useState(false);

  useEffect(()=>{try{const raw=localStorage.getItem(STORE);const parsed=raw?normalize(JSON.parse(raw)):blankState();setState(parsed);setSetupDate(parsed.examDate||'');setHydrated(true);}catch{setHydrated(true);}},[]);
  useEffect(()=>{if(hydrated)localStorage.setItem(STORE,JSON.stringify(state));},[state,hydrated]);
  useEffect(()=>{if(!hydrated||!state.setupComplete)return;const today=isoToday();if(parseDate(today).getDay()===1&&!restDateForWeek(state.rest,today))setRestPrompt(true);},[hydrated,state.setupComplete,state.rest]);

  const r=useMemo(()=>readiness(state),[state]);
  const today=isoToday();
  const days=daysRemaining(state.examDate);
  const due=tasksDueToday(state,today);
  const week=weekHours(state,today);
  const currentRest=restDateForWeek(state.rest,today);
  const cutoff=state.examDate?subtractMonths(state.examDate,2):null;
  const filteredRevision=useMemo(()=>{const all=state.revisionTasks; if(revisionFilter==='Due Today')return all.filter(t=>t.status!=='completed'&&t.dueDate===today);if(revisionFilter==='Overdue')return all.filter(t=>t.status!=='completed'&&t.dueDate<today).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));if(revisionFilter==='Upcoming')return all.filter(t=>t.status!=='completed'&&t.dueDate>today).sort((a,b)=>a.dueDate.localeCompare(b.dueDate));return all.filter(t=>t.status==='completed').sort((a,b)=>String(b.completedAt).localeCompare(String(a.completedAt)));},[state.revisionTasks,revisionFilter,today]);

  function saveExamDate(){if(!setupDate)return;setState(s=>({...s,examDate:setupDate,setupComplete:true}));}
  function setExamDate(value){setSetupDate(value);setState(s=>({...s,examDate:value,setupComplete:true}));}
  function openModule(moduleId){setModuleSelect(moduleId||'');setSessionDate(today);setSessionMinutes('60');setModuleDialog({moduleId:moduleId||null});}
  function logSession(){const id=moduleSelect;if(!id||!MODULE_BY_ID[id])return;const minutes=Math.max(1,Number(sessionMinutes)||0);const log={id:`log-${Date.now()}`,date:sessionDate,durationMinutes:minutes,moduleId:id};setState(s=>({...s,logs:[...s.logs,log]}));setModuleDialog(null);}
  function markIncomplete(){const id=moduleSelect;if(!id)return;setState(s=>{const existing=s.readingProgress[id];const count=Number(existing?.incompleteCount)||0;if(existing?.status==='completed'||count>=2)return s;const history=Array.isArray(existing?.history)?[...existing.history]:[];if(count===1){const idx=[...history].map((x,i)=>[x,i]).reverse().find(([x])=>x?.status==='incomplete')?.[1];if(idx!=null)history[idx]={...history[idx],credit:0.25};history.push({status:'incomplete',credit:0.25,at:new Date().toISOString()});}else history.push({status:'incomplete',credit:0.5,at:new Date().toISOString()});return {...s,readingDone:{...s.readingDone,[id]:false},readingProgress:{...s.readingProgress,[id]:{status:'incomplete',incompleteCount:count+1,credit:0.5,history}}};});setModuleDialog(null);}
  function markComplete(){const id=moduleSelect;const module=MODULE_BY_ID[id];if(!module)return;setState(s=>{const existing=s.readingProgress[id];if(existing?.status==='completed')return s;const progress={status:'completed',incompleteCount:Number(existing?.incompleteCount)||0,credit:1,history:[...(existing?.history||[]),{status:'completed',credit:1,at:new Date().toISOString()}]};const completionDate=today;const tasks=revisionSchedule(module,completionDate,s.examDate).map(t=>({...t,taskId:`${id}:${t.reviewType.replace(/[^a-z0-9]/gi,'').toLowerCase()}`}));const oldTasks=s.revisionTasks.filter(t=>t.moduleId!==id);return {...s,readDone:[...new Set([...s.readDone,id])],readingDone:{...s.readingDone,[id]:true},readingProgress:{...s.readingProgress,[id]:progress},completionDates:{...s.completionDates,[id]:completionDate},revisionTasks:[...oldTasks,...tasks]};});setModuleDialog(null);}
  function uncomplete(){const id=moduleSelect;if(!id)return;setState(s=>{const revisionTasks=s.revisionTasks.filter(t=>t.moduleId!==id);const revisionHistory=s.revisionHistory.filter(x=>x.moduleId!==id);const readDone=s.readDone.filter(x=>x!==id);const readingDone={...s.readingDone};delete readingDone[id];const readingProgress={...s.readingProgress};delete readingProgress[id];const completionDates={...s.completionDates};delete completionDates[id];return {...s,readDone,readingDone,readingProgress,completionDates,revisionTasks,revisionHistory,revisionReadinessCredit:revisionTasks.reduce((a,t)=>a+(t.status==='completed'?Number(t.rewardCredit||0):0),0)};});setModuleDialog(null);}
  function completeRevision(task){setState(s=>{const target=s.revisionTasks.find(t=>t.taskId===task.taskId);if(!target||target.status==='completed')return s;const revisionTasks=s.revisionTasks.map(t=>t.taskId===task.taskId?{...t,status:'completed',completedAt:new Date().toISOString()}:t);const revisionHistory=[...s.revisionHistory,{...target,status:'completed',completedAt:new Date().toISOString()}];return {...s,revisionTasks,revisionHistory,revisionReadinessCredit:revisionTasks.reduce((a,t)=>a+(t.status==='completed'?Number(t.rewardCredit||0):0),0)};});}
  function updateQuiz(topicId,key,value){setState(s=>({...s,subjectQuizzes:s.subjectQuizzes.map(q=>q.topicId===topicId?{...q,[key]:value}:q)}));}
  function updateMock(id,key,value){setState(s=>({...s,mocks:s.mocks.map(m=>m.id===id?{...m,[key]:value}:m)}));}
  function finishMock(){if(!mockDialog)return;const score=Math.max(0,Math.min(100,Number(mockScore)));if(!Number.isFinite(score))return;const m=state.mocks.find(x=>x.id===mockDialog);if(!m)return;setState(s=>({...s,mocks:s.mocks.map(x=>x.id===mockDialog?{...x,score,done:true,completedAt:new Date().toISOString()}:x)}));setMockDialog(null);setMockScore('');}
  function addRest(date){setState(s=>({...s,rest:[...new Set([...s.rest,date])]}));setRestPrompt(false);}
  function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='cfa-l2-tracker-backup.json';a.click();URL.revokeObjectURL(url);}
  function importBackup(file){if(!file)return;const reader=new FileReader();reader.onload=e=>{try{const imported=normalize(JSON.parse(e.target.result));setState(imported);setSetupDate(imported.examDate||'');setConfirmImport(false);}catch{alert('Invalid backup file.');}};reader.readAsText(file);}
  function resetAll(){if(!window.confirm('Reset the entire tracker? This cannot be undone.'))return;localStorage.removeItem(STORE);const fresh=blankState();setState(fresh);setSetupDate('');setTab('Dashboard');}

  if(!hydrated)return <div className="welcome"><div className="small">Loading tracker…</div></div>;
  if(!state.setupComplete)return <div className="welcome"><div className="card welcome-card"><div className="eyebrow">CFA Level II</div><h1>Study Tracker</h1><p>A local-first command center for 51 Learning Modules, spaced revision, study logging, subject quizzes, and eight full mocks. Your data stays in this browser.</p><div className="setup"><div className="field"><label>Exam date</label><input className="input" type="date" value={setupDate} onChange={e=>setSetupDate(e.target.value)} /></div><button className="btn" disabled={!setupDate} onClick={saveExamDate}>Enter Dashboard</button></div><div className="divider"/><div className="small">Estimated planned allocation: 300 hours across the curriculum. Hours are planning guidance only and never determine readiness.</div></div></div>;

  return <div className="app">
    <header className="shell header"><div><div className="eyebrow">CFA Level II · {formatDate(state.examDate)} exam</div><div className="title">Study Tracker</div></div><div className="countdown"><strong>{days}</strong><span>days remaining</span></div></header>
    <nav className="nav"><div className="shell nav-inner">{['Dashboard','Topics','Revision','Study Log','Mocks'].map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</div></nav>
    <main className="shell main">
      {tab==='Dashboard'&&<Dashboard state={state} r={r} today={today} due={due} week={week} streak={streak(state,today)} currentRest={currentRest} onTask={completeRevision} onQuiz={(id)=>updateQuiz(id,'done',true)} onOpenModule={openModule} onTab={setTab}/>} 
      {tab==='Topics'&&<Topics state={state} onOpenModule={openModule} onExamDate={setExamDate} examDate={state.examDate}/>} 
      {tab==='Revision'&&<Revision state={state} today={today} cutoff={cutoff} filter={revisionFilter} setFilter={setRevisionFilter} tasks={filteredRevision} onComplete={completeRevision} onQuiz={updateQuiz}/>} 
      {tab==='Study Log'&&<StudyLog state={state} onAdd={()=>openModule(null)} onDelete={id=>setState(s=>({...s,logs:s.logs.filter(l=>l.id!==id)}))}/>} 
      {tab==='Mocks'&&<Mocks state={state} onTarget={(id,v)=>updateMock(id,'targetDate',v)} onOpen={m=>{setMockDialog(m.id);setMockScore(m.score??'')}}/>}
      <div className="footer-actions"><button className="btn ghost" onClick={exportBackup}>Export JSON</button><label className="btn ghost">Import JSON<input hidden type="file" accept="application/json" onChange={e=>importBackup(e.target.files?.[0])}/></label><button className="btn ghost" onClick={resetAll}>Reset</button></div>
    </main>

    {moduleDialog&&<ModuleDialog module={MODULE_BY_ID[moduleSelect]} moduleSelect={moduleSelect} setModuleSelect={setModuleSelect} state={state} sessionDate={sessionDate} setSessionDate={setSessionDate} sessionMinutes={sessionMinutes} setSessionMinutes={setSessionMinutes} onClose={()=>setModuleDialog(null)} onLog={logSession} onComplete={markComplete} onIncomplete={markIncomplete} onUncomplete={uncomplete}/>} 
    {mockDialog&&<div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>{state.mocks.find(m=>m.id===mockDialog)?.title}</h2><p>Enter the final score to record completion.</p></div><button className="icon-btn" onClick={()=>setMockDialog(null)}>×</button></div><div className="modal-body"><div className="field"><label>Score · 0–100</label><input autoFocus className="input" type="number" min="0" max="100" value={mockScore} onChange={e=>setMockScore(e.target.value)}/></div><div className="notice" style={{marginTop:12}}>Mock readiness is fixed at 3.75% per completed mock. The score affects only the trend chart.</div><div className="modal-actions"><button className="btn ghost" onClick={()=>setMockDialog(null)}>Cancel</button><button className="btn" onClick={finishMock}>Complete Mock</button></div></div></div></div>}
    {restPrompt&&<RestModal onSelect={addRest} onSkip={()=>setRestPrompt(false)}/>} 
  </div>;
}

function Dashboard({state,r,today,due,week,streak,currentRest,onTask,onQuiz,onOpenModule,onTab}){const weekDays=Array.from({length:7},(_,i)=>{const d=parseDate(today);const day=d.getDay()||7;d.setDate(d.getDate()-day+1+i);return d.toISOString().slice(0,10)});return <>
  <div className="grid grid-2"><div className="card pad"><div className="ring-wrap"><div className="ring" style={{'--p':r.total}}><div className="ring-content"><strong>{r.total.toFixed(1)}%</strong><span>readiness</span></div></div><div className="breakdown">{[['First Pass',r.first,50],['Spaced Revision',r.revision,20],['Mock Gauntlet',r.mocks,30]].map(([n,v,max])=><div className="bar-row" key={n}><div className="bar-label"><span>{n}</span><span>{v.toFixed(1)} / {max}</span></div><div className="bar"><i style={{width:`${Math.min(100,v/max*100)}%`}}/></div></div>)}</div></div></div><div className="grid grid-4"><div className="card pad metric"><div className="label">Modules</div><div className="value">{state.readDone.length} / 51</div><div className="sub">completed</div></div><div className="card pad metric"><div className="label">Study Hours</div><div className="value">{(state.logs.reduce((a,l)=>a+l.durationMinutes,0)/60).toFixed(1)}</div><div className="sub">cumulative</div></div><div className="card pad metric"><div className="label">This Week</div><div className="value">{week.toFixed(1)}</div><div className="sub">hours logged</div></div><div className="card pad metric"><div className="label">Streak</div><div className="value">{streak}</div><div className="sub">active days</div></div></div></div>
  <div className="section-head"><div><h2>Tasks Due Today</h2><p>Revision tasks and subject quizzes scheduled for {formatDate(today)}.</p></div><span className="pill">{due.length} due</span></div><div className="card pad"><div className="task-list">{due.length?due.map(t=><div className="task" key={`${t.type}-${t.id}`}><div><div className="task-title">{t.title}</div><div className="task-meta">{t.meta}</div></div>{t.type==='revision'?<button className="btn" onClick={()=>onTask(state.revisionTasks.find(x=>x.taskId===t.id))}>Mark Done</button>:<button className="btn" onClick={()=>onQuiz(t.id)}>Complete Quiz</button>}</div>):<div className="empty">No tasks due today.</div>}</div></div>
  <div className="section-head"><div><h2>Weekly Activity Planner</h2><p>Rest days preserve your study streak and require no logged hours.</p></div>{currentRest&&<span className="pill">Rest: {formatShort(currentRest)}</span>}</div><div className="week">{weekDays.map(d=>{const hrs=state.logs.filter(l=>l.date===d).reduce((a,l)=>a+l.durationMinutes/60,0);const rest=state.rest.includes(d);return <div key={d} className={`day ${d===today?'today':''} ${rest?'rest':''}`}><div className="day-top"><span>{parseDate(d).toLocaleDateString('en-IN',{weekday:'short'})}</span><span>{formatShort(d)}</span></div><div className="day-hours">{hrs.toFixed(1)}h</div>{rest&&<div className="rest-label">REST</div>}</div>})}</div>
  <div className="section-head"><div><h2>Quick Actions</h2><p>All module actions open the same linked module dialog.</p></div></div><div className="grid grid-3"><button className="card pad btn" style={{textAlign:'left'}} onClick={()=>onTab('Topics')}>Review Topics →</button><button className="card pad btn" style={{textAlign:'left'}} onClick={()=>onTab('Study Log')}>Log Study Session →</button><button className="card pad btn" style={{textAlign:'left'}} onClick={()=>onTab('Revision')}>Open Revision Queue →</button></div>
</>}

function Topics({state,onOpenModule,onExamDate,examDate}){return <><div className="card pad"><div className="section-head" style={{marginTop:0}}><div><h2>Exam Configuration</h2><p>Changing the exam date updates the countdown and the two-calendar-month bonus-review cutoff.</p></div><div className="field" style={{minWidth:190}}><input className="input" type="date" value={examDate||''} onChange={e=>onExamDate(e.target.value)}/></div></div></div><div className="section-head"><div><h2>Curriculum · 51 Learning Modules</h2><p>Estimated allocation is fixed planning guidance; hours logged never determine completion or readiness.</p></div></div><div className="grid grid-2">{TOPICS.map((topic,tIndex)=><div className="card topic-card" key={topic.id}><div className="topic-top"><div><div className="topic-name">{topic.name}</div><div className="topic-meta">{topic.modules.length} modules · {topic.weight}% readiness weight · {topic.hours.reduce((a,b)=>a+b,0)} planned hours</div></div><span className="pill">{topic.modules.reduce((n,_,i)=>n+(state.readingProgress[`${topic.id}:${i+1}`]?.status==='completed'?1:0),0)}/{topic.modules.length}</span></div><div className="module-list">{topic.modules.map((title,i)=>{const id=`${topic.id}:${i+1}`;const p=state.readingProgress[id];const status=p?.status==='completed'?'Done':p?.status==='incomplete'?'Incomplete':'Not started';return <div className="module-row" key={id} onClick={()=>onOpenModule(id)}><input type="checkbox" readOnly checked={status==='Done'}/><div className="module-no">{String(MODULES.findIndex(m=>m.id===id)+1).padStart(2,'0')}</div><div className="module-title">{title}</div><div className="module-hours">{topic.hours[i]}h</div><div className={`module-status ${status==='Done'?'status-done':status==='Incomplete'?'status-incomplete':''}`}>{status}</div><div className="module-status">Open →</div></div>})}</div></div>)}</div></>}

function Revision({state,today,cutoff,filter,setFilter,tasks,onComplete,onQuiz}){return <><div className="grid grid-3"><div className="card pad metric"><div className="label">Core Reward</div><div className="value">{CORE_REWARD.toFixed(3)}%</div><div className="sub">per completed D+1 / D+7 / D+21 task</div></div><div className="card pad metric"><div className="label">Revision Earned</div><div className="value">{Math.min(20,state.revisionReadinessCredit||0).toFixed(1)}%</div><div className="sub">permanent, idempotent credit</div></div><div className="card pad metric"><div className="label">Bonus Cutoff</div><div className="value" style={{fontSize:18}}>{formatDate(cutoff)}</div><div className="sub">core tasks remain immune to cutoff</div></div></div><div className="section-head"><div><h2>Spaced Revision</h2><p>Core reviews are always created on module completion. Bonus retention reviews begin at D+42.</p></div><div className="seg">{['Due Today','Overdue','Upcoming','Completed History'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div></div><div className="card pad"><div className="task-list">{tasks.length?tasks.map(t=><div className="task" key={t.taskId}><div><div className="task-title">{t.moduleTitle}</div><div className="task-meta">{t.reviewType} · due {formatDate(t.dueDate)} {t.core?'· core':''}</div></div>{t.status==='completed'?<span className="pill">Completed</span>:<button className="btn" onClick={()=>onComplete(t)}>Mark Done</button>}</div>):<div className="empty">No revision tasks in this view.</div>}</div></div><div className="section-head"><div><h2>Subject Quizzes</h2><p>One overarching quiz per topic. Target dates drive the Dashboard due-today list.</p></div></div><div className="card pad"><table className="table"><thead><tr><th>Topic</th><th>Target Date</th><th>Status</th></tr></thead><tbody>{state.subjectQuizzes.map(q=><tr key={q.topicId}><td>{q.topicName}</td><td><input className="input" style={{maxWidth:160}} type="date" value={q.targetDate||''} onChange={e=>onQuiz(q.topicId,'targetDate',e.target.value||null)}/></td><td style={{textAlign:'right'}}><button className="btn" onClick={()=>onQuiz(q.topicId,'done',!q.done)}>{q.done?'Done':'Mark Done'}</button></td></tr>)}</tbody></table></div></>}

function StudyLog({state,onAdd,onDelete}){const total=state.logs.reduce((a,l)=>a+l.durationMinutes,0);const avg=state.logs.length?total/state.logs.length:0;return <><div className="section-head" style={{marginTop:0}}><div><h2>Study Log</h2><p>Manual sessions are linked to a specific Learning Module. Logging hours is independent of readiness.</p></div><button className="btn" onClick={onAdd}>+ Log Study Session</button></div><div className="grid grid-3"><div className="card pad metric"><div className="label">Total Hours</div><div className="value">{(total/60).toFixed(1)}</div></div><div className="card pad metric"><div className="label">Sessions</div><div className="value">{state.logs.length}</div></div><div className="card pad metric"><div className="label">Average Session</div><div className="value">{avg.toFixed(0)}m</div></div></div><div className="card pad" style={{marginTop:14}}><table className="table"><thead><tr><th>Date</th><th>Module</th><th>Duration</th><th></th></tr></thead><tbody>{[...state.logs].sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id)).map(l=><tr key={l.id}><td>{formatDate(l.date)}</td><td>{MODULE_BY_ID[l.moduleId]?.title||'—'}</td><td>{l.durationMinutes} min</td><td><button className="btn ghost" onClick={()=>onDelete(l.id)}>Delete</button></td></tr>)}</tbody></table>{!state.logs.length&&<div className="empty">No study sessions yet.</div>}</div></>}

function Mocks({state,onTarget,onOpen}){const points=chartPoints(state.mocks);return <><div className="section-head" style={{marginTop:0}}><div><h2>Mock Gauntlet</h2><p>Eight full single-session mocks. Each completed mock contributes exactly 3.75% readiness.</p></div></div><div className="mock-grid">{state.mocks.map(m=><div className="card mock" key={m.id}><h3>{m.title}</h3><div className={`score ${m.done?'':'pending'}`}>{m.done?`${m.score}`:'—'}</div><div className="small">{m.done?`completed ${formatShort(m.completedAt?.slice(0,10))}`:'not completed'}</div><div className="divider"/><div className="field"><label>Target date</label><input className="input" type="date" value={m.targetDate||''} onChange={e=>onTarget(m.id,e.target.value||null)}/></div><button className="btn" style={{marginTop:9,width:'100%'}} onClick={()=>onOpen(m)}>{m.done?'Update Score':'Complete Mock'}</button></div>)}</div><div className="section-head"><div><h2>Score Trend</h2><p>Completed mock scores only; score does not affect readiness.</p></div></div><div className="card chart"><div className="chart-grid"><div className="chart-line"/><div className="chart-line"/><div className="chart-line"/><div className="chart-line"/><div className="chart-line"/></div>{points?<svg className="chart-svg" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={points} fill="none" stroke="#e2e8f0" strokeWidth="1.2" vectorEffect="non-scaling-stroke"/><g>{state.mocks.filter(m=>m.done&&m.completedAt&&typeof m.score==='number').map((m,i)=>{const done=state.mocks.filter(x=>x.done&&x.completedAt&&typeof x.score==='number');const x=5+(i/(Math.max(done.length-1,1)))*90;const y=95-(m.score/100)*90;return <circle key={m.id} cx={x} cy={y} r="1.6" fill="#e2e8f0"/>})}</g></svg>:<div className="empty" style={{position:'absolute',inset:18}}>Complete mocks to populate the score trend.</div>}<div className="chart-axis"><span>0</span><span>25</span><span>50</span><span>75</span><span>100</span></div></div></>}

function ModuleDialog({module,moduleSelect,setModuleSelect,state,sessionDate,setSessionDate,sessionMinutes,setSessionMinutes,onClose,onLog,onComplete,onIncomplete,onUncomplete}){const p=module?state.readingProgress[module.id]:null;const complete=p?.status==='completed';const incompleteCount=Number(p?.incompleteCount)||0;return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>{module?module.title:'Log Study Session'}</h2><p>{module?`${module.topicName} · planned ${module.plannedHours}h`:'Select a module, then log time or update its completion status.'}</p></div><button className="icon-btn" onClick={onClose}>×</button></div><div className="modal-body"><div className="field"><label>Learning Module</label><select className="select" value={moduleSelect} onChange={e=>setModuleSelect(e.target.value)}><option value="">Select a module…</option>{TOPICS.map(t=><optgroup key={t.id} label={t.name}>{t.modules.map((title,i)=>{const id=`${t.id}:${i+1}`;return <option key={id} value={id}>{String(MODULES.findIndex(m=>m.id===id)+1).padStart(2,'0')} · {title}</option>})}</optgroup>)}</select></div>{module&&<><div className="two-col" style={{marginTop:12}}><div className="notice"><b>Status</b><br/>{complete?'Completed':p?.status==='incomplete'?`Incomplete · attempt ${incompleteCount}/2`:'Not started'}</div><div className="notice"><b>Revision</b><br/>{complete?`${state.revisionTasks.filter(t=>t.moduleId===module.id&&t.status==='completed').length} tasks completed`:'Created after completion'}</div></div><div className="divider"/></>}<div className="two-col"><div className="field"><label>Study date</label><input className="input" type="date" value={sessionDate} onChange={e=>setSessionDate(e.target.value)}/></div><div className="field"><label>Duration · minutes</label><input className="input" type="number" min="1" value={sessionMinutes} onChange={e=>setSessionMinutes(e.target.value)}/></div></div><div className="notice" style={{marginTop:12}}>Study hours are recorded for analytics and weekly activity only. They do not affect module completion or readiness.</div>{module&&<div className="notice" style={{marginTop:8}}>Incomplete rules: attempt 1 = 0.50 credit; attempt 2 rewrites the earlier 0.50 to 0.25 and adds 0.25. A third incomplete attempt is blocked. Completion awards 1.00 and creates D+1, D+7 and D+21 core reviews.</div>}<div className="modal-actions"><button className="btn ghost" onClick={onClose}>Cancel</button><button className="btn" disabled={!moduleSelect} onClick={onLog}>Log Session</button>{module&&!complete&&<button className="btn ghost" disabled={incompleteCount>=2} onClick={onIncomplete}>Incomplete</button>}{module&&!complete&&<button className="btn" onClick={onComplete}>Completed</button>}{module&&complete&&<button className="btn ghost" onClick={onUncomplete}>Uncheck Completed</button>}</div></div></div></div>}

function RestModal({onSelect,onSkip}){const today=isoToday();const d=parseDate(today);const day=d.getDay()||7;const monday=new Date(d);monday.setDate(d.getDate()-day+1);const days=Array.from({length:7},(_,i)=>{const x=new Date(monday);x.setDate(monday.getDate()+i);return x.toISOString().slice(0,10)});return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><h2>Plan Your Week</h2><p>Select your designated rest day for this week:</p></div></div><div className="modal-body"><div className="grid grid-2">{days.map(x=><button key={x} className="btn" onClick={()=>onSelect(x)}>{parseDate(x).toLocaleDateString('en-IN',{weekday:'long'})}<br/><span className="small">{formatShort(x)}</span></button>)}</div><div className="modal-actions"><button className="btn ghost" onClick={onSkip}>Skip / Train Everyday</button></div></div></div></div>}
